### ISSUE TITLE
Errors when trying to build on our EC2 server

### ISSUE THREAD

**Issue by clemp** [DiamondDAO/chainverse-frontend#2]
There's a good chance I'm missing a step or doing something wrong..

However, when I run the command `npm run build` on our EC2 server, I get the follow errors:

![image](https://user-images.githubusercontent.com/5624429/145115998-06b412e3-3bbd-45e9-83cf-612b88ff2208.png)

The main error (not just warning) is pointing to the DateFilter.tsx file: https://github.com/DiamondDAO/chainverse-frontend/blob/main/components/Navbar/DateFilter.tsx

Any idea what the issue could be?

**Comment by musubipapi** [comment]
hey @clemp -- just merged in a fix from this PR https://github.com/DiamondDAO/chainverse-frontend/pull/3. The issue was typing related from a typescript check I had on which would flag when images lack the `alt` tag.

**Comment by clemp** [comment]
@musubipapi this fixed the issue. Nice work, will close this.
