### ISSUE TITLE
Do work necessary to deploy Twitter bot to dev-chainverse

### ISSUE THREAD

**Issue by clemp** [DiamondDAO/chainverse-frontend#34]
During the onboarding flow a user is asked to submit their Twitter handle. Currently that creates `Wallet -[:CREATED]-> Response` relationship between nodes.

```
match p=(w:Wallet)-[r:CREATED]->(n:Response)
where n.text = "c_lemp"
return p
```
![image](https://user-images.githubusercontent.com/5624429/162036844-4c8c78ee-7de8-4715-94b5-f50c31bc760e.png)

We need to enhance this flow in two ways:

1) Define a relation ontology for `Wallet -[:?] -> Account:Twitter` @Azharo 
2) Create a lookup to the Twitter API that: 
    - Requests `twitterId` from the Twitter API
    -  Merges with any `Account:Twitter` nodes in the database already on that `twitterId`
    -  Writes the ontology defined in Step 1.

**Comment by liminal-dog** [comment]
We should also make sure that we make whatever adjustments are necessary to ensure that blocks created with the Twitter bot are visible in a user's blocks.

**Comment by liminal-dog** [comment]
Would deploying the Twitter bot be included in this ticket?

**Comment by clemp** [comment]
@liminal-dog yes completing this modular component of a Twitter username <> id lookup would be a requirement for the phase one twitter bot.

Ideally this lookup solution should be built as a separate data utility within `chainverse-backend`.

For example:

```
chainverse-backend
    apps
        snapshot-ingest
        twitter-ens-pipeline
        mirror-xyz-pipeline
        chainverse-bot
        ...
    packages
        twitter-id-lookup
```

and then when one of the ingest pipelines needs to utilize this Twitter lookup function it gets imported

```js
import { getTwitterIdFromUsername } from "../packages/twitter-id-lookup
````

**Comment by rohanbansal12** [comment]
do we need a whole package for this? Its like two lines of code

**Comment by Azharo** [comment]
Ontology for this process should be:
(:Wallet)-[:HAS]->(:Twitter:Account)

So flow here would be:
1) User enters Twitter ID
2) twitter-id-lookup gets the id of the username
3) username and id and wallet sent to Neo4j as the following query:
`MERGE (a:Wallet {address: toLower($address)})
MERGE (b:Twitter:Account {twitterId: $id})
SET a.username = $username
MERGE (a)-[:HAS]->(b)`

**Comment by clemp** [comment]
> do we need a whole package for this? Its like two lines of code

My thinking of making this a package/utility is that this pattern of looking up a Twitter id could be reused in several ingest pipelines. So instead of each developer of a pipeline that needs this functionality having to figure out the Twitter API keys, function logic, data integrity, etc we release as a package to abstract those details, and import the package as needed.

What are those two lines of code you're thinking?

**Comment by rohanbansal12** [comment]
const response = await client.userByUsername("<username>");
const userId = response.data.id;

**Comment by clemp** [comment]
As long as you think the code is modular enough to be plugged in and reused by the various data pipelines that will need this engineering pattern

**Comment by rohanbansal12** [comment]
Okay yeah, the only consideration is if you want the wrapper to also initialize the Twitter API client itself, then we could set up a function. I'm not sure what design pattern we want to go for though. I'm not a fan of creating the client each time we want to pull in a single amount of data.

**Comment by liminal-dog** [comment]
Hey what's the status here? Are we still on track to push this today?

**Comment by clemp** [comment]
This is not fully implemented yet. @rohanbansal12 and I tested the ingestion of `@enterchainverse !bot` replies, and that part is working as intended.

**Twitter bot**

Ran in a sandbox to collect recent tweets. Here's one example of the ingest working as intended:
```cypher
match p=(t:Account)-[:TWEETED]-(tweet:Tweet)-[]-()-[:TWEETED]-(t2:Tweet) 
where t.username = "amphib0ly" 
and tweet.url = "https://twitter.com/amphib0ly/status/1519158498986184705"
return p
```

![image](https://user-images.githubusercontent.com/5624429/165587200-6ebdaea5-0848-4508-80a6-6c559e6a629d.png)

**Chainverse UI integration**

To then connect the `Twitter:Account` node of the Twitter user who created the `@enterchainverse` reply tweet to the Chainverse user who is using the application is a bit tricky - this is what we're working on now.

For example:

In the current onboarding flow a user connects their wallet and responds to the `Prompt` `"What's your Twitter handle?". This is written to the Neo4j database in this form: 

![image](https://user-images.githubusercontent.com/5624429/165588953-3921a5cf-db5e-481f-ac25-ab41b897e92f.png)

The Twitter username is written to a `Block:Response` node with the `text` property that contains the username. Ideally we want to merge nodes on the `twitter_id` field because usernames can change.

So for now, we're going to implement a temp solution to get the feature working, but needs a better solution if this is a feature we want to maintain over time.

**Current solution**
1. Ingest `@enterchainverse` data into the database
2. Identify user Twitter accounts with the query `match (b:Block)-[:RESPONDS_TO]->(p:Prompt) where p.text = "What's your Twitter handle?" return b`
3. Run a program that pings the Twitter API to look up the `twitter id` for nodes returned in Step 2
4. Merge nodes into a `Twitter:Account` node connected to the Chainverse user's `Wallet` node

Once complete, the tweets from the `@enterchainverse` bot will appear in the Chainverse user's `My Blocks` section.

**Comment by clemp** [comment]
I did QA and pushed a couple of commits today toward this issue.

**Chainverse bot**

This app now successfully reads in the previous 7 days of Twitter data (looks for the `@chainverse !bot <...>` reply pattern) https://github.com/DiamondDAO/chainverse-backend/commit/0ace80489f136109fef186c50e9ef3f36ca91bd7

**Ad hoc Twitter cleanup**

For steps 2-3 in the previous issue an ad hoc script was created to clean up the nodes and relations https://github.com/DiamondDAO/chainverse-backend/commit/f1487a16e7d8d24a636ac5496cb37a710d2bf27e

![image](https://user-images.githubusercontent.com/5624429/165861089-32555bff-29b5-4337-83e9-7fa404257e99.png)

**Frontend displaying `chainverse bot` tweets as `Blocks`**

![image](https://user-images.githubusercontent.com/5624429/165861214-3bbcb3d1-a5e8-4202-8d10-5aab0e1a2d34.png)

So, the data shows up. However, the display and details on those blocks is still sparse, very preliminary.

**Comment by fmeiraf** [comment]
Suggestions for future improvements for people to get more context on the tweet being used: 

- Highlight the thread link in the block.
- we could have an embed widget that could pull more info / show the thread in its completion.

**Comment by clemp** [comment]
Going to put this issue back in the backlog for future Chainverse features. Based on product feedback, strategy, and engineering effort to get this done right, it's not a main focus to implement this at the moment.

**Comment by clemp** [comment]
Closing for now, will revisit if we consider this feature in the future.
