### ISSUE TITLE
Onboarding survey responses need relations to the question being asked

### ISSUE THREAD

**Issue by clemp** [DiamondDAO/chainverse-frontend#35]
Currently when the user responds to the initial survey a `Wallet -[:CREATES]-> Response` relation is generated.

```
match p=(w:Wallet)-[r:CREATED]->(n:Response)
where w.address = "0x97b9958faceC9ACB7ADb2Bb72a70172CB5a0Ea7C"
return p
```

![image](https://user-images.githubusercontent.com/5624429/162040494-c43c8703-ef33-414c-beda-a18f80804890.png)

However, what's missing is context about what the `Response` is actually in response to. 

At one point an ontology like `User -{:SELECTED]-> Response -[:RESPONDS_TO]-> Prompt:Survey` was discussed. @Azharo thoughts on this? Also, we don't currently have a `User` node implemented and separate from the `Wallet` node used to connect.

![image](https://user-images.githubusercontent.com/5624429/162040832-8f3ed20c-fbf0-4700-81b5-3837d9e2c9f4.png)

I think the part of the code to review is here
https://github.com/DiamondDAO/chainverse-frontend/blob/2501409cc02ae58f367d93769608c13168a7975d/src/services/Apollo/Mutations.ts#L24-L38

and/or here
https://github.com/DiamondDAO/chainverse-frontend/blob/2501409cc02ae58f367d93769608c13168a7975d/src/pages/onboard/index.page.tsx#L34-L54

**Comment by liminal-dog** [comment]
The current on-boarding flow is creating unnecessary friction for users (being trimmed down pursuant to another issue). That being said, something like our current on-boarding flow may be helpful in the future for certain user groups (i.e. talent network participants). Would recommend moving to backlog.
