### ISSUE TITLE
Reduce onboarding flow steps

### ISSUE THREAD

**Issue by angelaliu22** [DiamondDAO/chainverse-frontend#38]
Remove all questions except:

Wallet address
Method of contact

**Comment by clemp** [comment]
@musubipapi if this issue is done, would you link the corresponding pull request or commit here please?

**Comment by liminal-dog** [comment]
Hey @angelaliu22 @musubipapi -- 

Can someone please share what steps are expected in the onboarding flow so I can verify that the one's we wanted to remove are in fact removed? they're still showing up in the testing app

**Comment by clemp** [comment]
Address this here: https://github.com/DiamondDAO/chainverse-frontend/pull/70
