### ISSUE TITLE
Hide/comment out all buttons that don't have working functionality yet

### ISSUE THREAD

**Issue by angelaliu22** [DiamondDAO/chainverse-frontend#39]
1. View graph in the slideout
2. View graph in search results' rows
3. Explorer - past searches
4. Explorer - recommenations
5. Workspace - My narratives
6. Search autocomplete dropdown - autocompleted results section (entities, tags, blocks) 

We should re-enable 1, 2, 6 when Graph view is complete

**Comment by clemp** [comment]
@musubipapi if this issue is done, would you link the corresponding pull request or commit here please?
