### ISSUE TITLE
Reduce friction for executing a search

### ISSUE THREAD

**Issue by liminal-dog** [DiamondDAO/chainverse-frontend#40]
This item was also in the Q/A backlog but re-raising because I've seen multiple people struggle with completing a search because they expect to be able to click on a result and can't.

One (Eric Mack) told me that he assumed search didn't work because he couldn't do this. "Oh wow, I have never seen this results table."

A few options for resolving:
- Allowing people to click on a result and immediately display the result in the "results view"
- Removing the search preview

**Comment by angelaliu22** [comment]
Do you mean in the search auto-complete dropdown? The feature to click one of the options under "Entities, Tags, Blocks" just hasn't been built out yet. The user should be able to click on one of those results and be brought straight to the graph.

**Comment by liminal-dog** [comment]
Right -- as discussed I think we should remove until that feature is built out.
