### ISSUE TITLE
Review ontology for `Entity` unique ids needed for front-end features

### ISSUE THREAD

**Issue by clemp** [DiamondDAO/chainverse-frontend#42]
@musubipapi raised an issue around unique id's encoded in various `Entity` nodes, according to our ontology. It seems like we need to review and perhaps modify how nodes are identified uniquely to enable some features of the Chainverse front-end.

**Comment by Azharo** [comment]
Reviewed on Thursday with @musubipapi. Solution being attempted is to instead create a Union in GraphQL between the different Entities (Snapshot and DaoHaus) and search by the name property.
