### ISSUE TITLE
Add key context to entity profiles

### ISSUE THREAD

**Issue by liminal-dog** [DiamondDAO/chainverse-frontend#47]
# PRD
- *In progress*

# Wishlist items
Need to discuss which items are addressable using existing data & given time constraints with Angela, Omar, and Andy and add to PRD.

## Descriptive context
- Twitter
- Website
- Discord
- DAOhaus profile (if applicable)
- Snapshot profile (if applicable)
- Link to forum (if available)
- Etherscan for token contract (if applicable)

## Analytic context
- Number of members (DAOhaus DAO)
- Number of token holders (Snapshot DAO)

**Comment by Azharo** [comment]
Items currently available:
For DaoHaus Entities. Need to look into how to add for Snapshot
- Twitter (t:Entity) t.twitter
- Forum (w:Entity) w.forum
- Discord (d:Entity) d.forum
- Blob (b:Entity) b.blog
- OpenSea (o:Entity) o.opensea
- Documentation (d:Entity) d.documentation

Items that we can probably create fairly quickly via a simple query as part of the front-end:
- # of members (DAOHaus DAO)
`MATCH (:DAOHaus:Entity:Dao)<-[:IS_MEMBER]-(m:Member)
RETURN COUNT(distinct m)`
- # of token holders (Snapshot DAO)
'MATCH (:Snapshot:Space:Entity)-[:HAS_PROPOSAL]->(:Proposal)<-[:VOTED]-(w:Wallet)
RETURN COUNT(distinct w)'

**Comment by liminal-dog** [comment]
Nice. Do you have thoughts on how to break this out into tasks?

**Comment by Azharo** [comment]
Yes, this needs to be broken out as a single query function to be run once the user selects Entity. I'll create a separate issue for the front-end.

**Comment by rohanbansal12** [comment]
@Azharo The Snapshot API returns some of this information already. For the remaining fields, we can by default initialize them to empty or just not set them, then have a separate pipeline for adding manually collected data.

**Comment by liminal-dog** [comment]
@Azharo @musubipapi @clemp curious to hear everyone's thoughts on the relative merits of storing identifiers (i.e. Twitter, Discord) as properties on the `Entity` node versus independent nodes? 

It seems like breaking out identifiers into their nodes could solve some existing problems and open up some opportunities:

*Simplifying existing problems*
- It seems like we've been doing some thinking about how to deal with different types of entities having different properties. Would breaking out identifiers simplify the Entity ontology in any sort of useful way?
- Some entities have multiple identifiers, would breaking them out into separate nodes have any benefits for us?

*Consistency*
- In some cases (i.e. Twitter) we already break out identifiers as separate nodes.

*Opportunities*
- There are cases where entities share identifiers (i.e. Diamond Bank and Diamond DAO share a Twitter account). This could help us link DAOs and other entities that are controlled by the same ultimate entity or have some other sort of meaningful relationship.
- If we want to ingest data from more sources that involve identifiers (i.e. Discord) it seems like it would be helpful for those spaces to be their own objects
- ability to add context/metadata about identifiers (i.e. the source we collected them from, the date we collected, etc)

**Comment by Azharo** [comment]
They should be broken out. It adds another dimension by which we can take advantage of the relationship to these identifiers like for example if a DAO's Twitter or blog is very active we would have other nodes having relationships to that Twitter node

**Comment by clemp** [comment]
> They should be broken out. It adds another dimension by which we can take advantage of the relationship to these identifiers like for example if a DAO's Twitter or blog is very active we would have other nodes having relationships to that Twitter node

Interesting thought here.. how would you recommend the ontology for those `(Entity)-[:?]->(?)` relations? What would we name the nodes containing identifier information?
