### ISSUE TITLE
Delete block button in block slide out

### ISSUE THREAD

**Issue by liminal-dog** [DiamondDAO/chainverse-frontend#58]
Add “Delete block” button in Block slide out when Workspace view (along with Edit block, if applicable). See Figma attached. Have confirmation modal just like “Delete Workspace”. Text of modal should say: 

[](https://www.figma.com/file/sHfBJO5DPwU3ifPpzQY2eL/Chainverse-MVP?node-id=537%3A37075)Figma artboard: [https://www.figma.com/file/sHfBJO5DPwU3ifPpzQY2eL/Chainverse-MVP?node-id=537%3A37075](https://www.figma.com/file/sHfBJO5DPwU3ifPpzQY2eL/Chainverse-MVP?node-id=537%3A37075)

 

Modal copy:
Are you sure you want to delete the workspace? Deleting this workspace will not remove the nodes from the Chainverse graph.

**Comment by clemp** [comment]
Closing this for now due to inactivity - we can revisit during next design iterations
