### ISSUE TITLE
Entity description query for once user selects Entity

### ISSUE THREAD

**Issue by Azharo** [DiamondDAO/chainverse-frontend#65]
For [https://github.com/DiamondDAO/chainverse-frontend/issues/47](url), need to embed the following query to get back Entity descriptions for the front-end.

Flow:
1. User selects an Entity
2. Query below is run
3. Output from the query is shown in appropriate part of the UI

`MATCH (d:Entity {name:$name})`
`OPTIONAL MATCH (d)-[:HAS_PROPOSAL]->(:Proposal)<-[:VOTED]-(sm:Wallet)`
`WITH d, COUNT(DISTINCT sm) as snapshot_members`
`OPTIONAL MATCH (d)<-[:IS_MEMBER]-(dm:Member)`
`WITH d, snapshot_members, COUNT(DISTINCT dm) as DAOHaus_members`
`RETURN snapshot_members, DAOHaus_members, d.forum as forum, d.discord as discord, d.documentation as documentation, d.twitter as twitter, d.opensea as OpenSea, d.blog as blog`

See below for example execution with $name = 'Ricardian LLC DAO'. Query is fairly performant and runs pretty quickly
<img width="883" alt="image" src="https://user-images.githubusercontent.com/25023182/163859757-ed13147a-4019-4428-b4ed-541a73a4d5f8.png">

**Comment by clemp** [comment]
> `MATCH (d:Entity {name:$name})`
> `OPTIONAL MATCH (d)-[:HAS_PROPOSAL]->(:Proposal)<-[:VOTED]-(sm:Wallet)`
> `WITH d, COUNT(DISTINCT sm) as snapshot_members`
> `OPTIONAL MATCH (d)<-[:IS_MEMBER]-(dm:Member)`
> `WITH d, snapshot_members, COUNT(DISTINCT dm) as DAOHaus_members`
> `RETURN snapshot_members, DAOHaus_members, d.forum as forum, d.discord as discord, d.documentation as documentation, d.twitter as twitter, d.opensea as OpenSea, d.blog as blog`

This query assumes some properties that are not currently present in the type definitions for Entities. Here's the properties of `Entity` (as is currently in `develop`) 

https://github.com/DiamondDAO/chainverse-frontend/blob/cf064b815bb58336bed3d1d0ea721991deda5dbf/src/services/Apollo/typedefs.ts#L12-L27

I know @musubipapi is expanding these by creating unions of different `Entity` types; for example, `Entity:Snapshot` properties will be different than `Entity:DAOhaus` properties. 

@Azharo For the properties you list here above: `opensea`, `documentation`, etc - how do you envision these aligning to specific `Entity` types as laid out in the GraphQL API type definitions?

**Comment by Azharo** [comment]
These properties will eventually just get taken out as separate nodes attached to each :Entity which hasn't been done yet. That'll remove any problems with the union since right now the Union is only really going to have name property.
This way we can connect different Entities as the same entity if they reference the same descriptor such as they have the same twitter handle or medium. 
I'll add to issue that we need to expand these out as nodes and not keep as properties

Change current code snippet above to the following so it works even with our GraphQL types so at least we have it working in the UX while we make the right changes on the backend:

`MATCH (d:Entity {name:$name})
OPTIONAL MATCH (d)-[:HAS_PROPOSAL]->(:Proposal)<-[:VOTED]-(sm:Wallet)
WITH d, COUNT(DISTINCT sm) as snapshot_members
OPTIONAL MATCH (d)<-[:IS_MEMBER]-(dm:Member)
WITH d, snapshot_members, COUNT(DISTINCT dm) as DAOHaus_members
OPTIONAL MATCH (dao:DaoHaus:Dao {name:$name})
RETURN snapshot_members, DAOHaus_members, dao.forum as forum, dao.discord as discord, dao.documentation as documentation, dao.twitter as twitter, dao.opensea as OpenSea, dao.blog as blog`
