### ISSUE TITLE
No search results for blocks

### ISSUE THREAD

**Issue by liminal-dog** [DiamondDAO/chainverse-frontend#66]
No matter what I search I don't get search results for blocks, i.e. http://staging.chainverse.diamonds/explorer/search?term=diamond%20dao&type=blocks.

In addition to being a usability issue, it also makes it difficult for me to troubleshoot/q&a. For instance, I ran a migration to add blocks for Dan Wu but I cannot see if they show up in the UI because I am not getting any search results back.

**Comment by clemp** [comment]
While our search functionality has much room for improvement, this particular bug was addressed. Not sure which commit, but here's a screenshot of Blocks being returned by the search in the link above

![Image](https://user-images.githubusercontent.com/5624429/173447521-f6a63462-e354-4859-be7c-8736b326fd91.png)

Closing this issue now
