### ISSUE TITLE
Block -> Tag relationship fix

### ISSUE THREAD

**Issue by Azharo** [DiamondDAO/chainverse-frontend#68]
Current:
(:Block)-[IS_TAGGED]->(:Tag)

To keep it consistent with rest of ontology should change to:
(:Block)-[:HAS_TAG]->(:Tag)

**Comment by clemp** [comment]
Fixed this issue in this commit: https://github.com/DiamondDAO/chainverse-frontend/commit/b27b353883d82e3103a7d3d9c2d3d87118f87527
