### ISSUE TITLE
Users having issues editing blocks

### ISSUE THREAD

**Issue by liminal-dog** [DiamondDAO/chainverse-frontend#92]
Right now, users can only edit `Note` blocks from the `My Blocks` fly-out. 

Users cannot edit `Partnership` blocks or `Entity` blocks at all.

- [ ] User should be able to edit Partnership and Entity blocks (in the fly-out)
- [ ] User should be able to edit `Note` blocks (in the `My Blocks` page and from the note block fly out

**Comment by clemp** [comment]
Edit function works, but in the popup only for now. Waiting to integrate fly-out edits for the redesign. Closing this issue for now.

**Comment by liminal-dog** [comment]
As a matter of practice can we please alert the talent network channel when
we (1) merge a PR that involves a user-facing feature, (2) make a decision
where s feature in the application won't work (i.e. we won't do edits in
the fly out until we do the re-design)?

We will save our users a lot of time if we communicate what we do expect to
work and what we don't expect to work.
